import { jest } from '@jest/globals';
import rockPaperScissors from './rockPaperScissors.js';

describe('rockPaperScissors', () => {
  it('should exist', () => {
    expect(rockPaperScissors).toBeDefined();
  });

  it('should be a function', () => {
    expect(rockPaperScissors).toBeInstanceOf(Function);
  });

  it('should return an array', function() {
    expect(rockPaperScissors()).toBeInstanceOf(Array);
  });

  it('should return an array of strings', () => {
      expect(rockPaperScissors()[ 0 ]).toBeDefined();
      expect(typeof rockPaperScissors()[ 0 ]).toBe("string");
    });

  it('should contain every throw', () => {
      var expected = [
        'RRR', 'RRP',
        'RRS', 'RPR',
        'RPP', 'RPS',
        'RSR', 'RSP',
        'RSS', 'PRR',
        'PRP', 'PRS',
        'PPR', 'PPP',
        'PPS', 'PSR',
        'PSP', 'PSS',
        'SRR', 'SRP',
        'SRS', 'SPR',
        'SPP', 'SPS',
        'SSR', 'SSP',
        'SSS'
      ];
      var result = rockPaperScissors();
      expect(result.length).toBe(expected.length);
      expect(result).toEqual(expected);
    });


  describe('EXTRA CREDIT', function() {
    it('should return results for rockPaperScissors(2)', () => {
        let expected = [
          'RR',
          'RP',
          'RS',
          'PR',
          'PP',
          'PS',
          'SR',
          'SP',
          'SS'
        ];
        let result = rockPaperScissors(2);
        expect(result.length).toBe(expected.length);
        expect(result).toEqual(expected);
      });
    it('should return results for rockPaperScissors(1)', () => {
        let expected = [ 'R', 'P', 'S' ];
        let result = rockPaperScissors(1);
        expect(result.length).toBe(expected.length);
        expect(result).toEqual(expected);
      });
    it('should return results for rockPaperScissors(5)', () => {
        let expected = expectedOutputForRockPaperScissorsOf5();
        let result = rockPaperScissors(5);
        expect(result.length).toBe(expected.length);
        expect(result).toEqual(expected);
      });
  });

});


let expectedOutputForRockPaperScissorsOf5 = () => {
  return [
    'RRRRR',
    'RRRRP',
    'RRRRS',
    'RRRPR',
    'RRRPP',
    'RRRPS',
    'RRRSR',
    'RRRSP',
    'RRRSS',
    'RRPRR',
    'RRPRP',
    'RRPRS',
    'RRPPR',
    'RRPPP',
    'RRPPS',
    'RRPSR',
    'RRPSP',
    'RRPSS',
    'RRSRR',
    'RRSRP',
    'RRSRS',
    'RRSPR',
    'RRSPP',
    'RRSPS',
    'RRSSR',
    'RRSSP',
    'RRSSS',
    'RPRRR',
    'RPRRP',
    'RPRRS',
    'RPRPR',
    'RPRPP',
    'RPRPS',
    'RPRSR',
    'RPRSP',
    'RPRSS',
    'RPPRR',
    'RPPRP',
    'RPPRS',
    'RPPPR',
    'RPPPP',
    'RPPPS',
    'RPPSR',
    'RPPSP',
    'RPPSS',
    'RPSRR',
    'RPSRP',
    'RPSRS',
    'RPSPR',
    'RPSPP',
    'RPSPS',
    'RPSSR',
    'RPSSP',
    'RPSSS',
    'RSRRR',
    'RSRRP',
    'RSRRS',
    'RSRPR',
    'RSRPP',
    'RSRPS',
    'RSRSR',
    'RSRSP',
    'RSRSS',
    'RSPRR',
    'RSPRP',
    'RSPRS',
    'RSPPR',
    'RSPPP',
    'RSPPS',
    'RSPSR',
    'RSPSP',
    'RSPSS',
    'RSSRR',
    'RSSRP',
    'RSSRS',
    'RSSPR',
    'RSSPP',
    'RSSPS',
    'RSSSR',
    'RSSSP',
    'RSSSS',
    'PRRRR',
    'PRRRP',
    'PRRRS',
    'PRRPR',
    'PRRPP',
    'PRRPS',
    'PRRSR',
    'PRRSP',
    'PRRSS',
    'PRPRR',
    'PRPRP',
    'PRPRS',
    'PRPPR',
    'PRPPP',
    'PRPPS',
    'PRPSR',
    'PRPSP',
    'PRPSS',
    'PRSRR',
    'PRSRP',
    'PRSRS',
    'PRSPR',
    'PRSPP',
    'PRSPS',
    'PRSSR',
    'PRSSP',
    'PRSSS',
    'PPRRR',
    'PPRRP',
    'PPRRS',
    'PPRPR',
    'PPRPP',
    'PPRPS',
    'PPRSR',
    'PPRSP',
    'PPRSS',
    'PPPRR',
    'PPPRP',
    'PPPRS',
    'PPPPR',
    'PPPPP',
    'PPPPS',
    'PPPSR',
    'PPPSP',
    'PPPSS',
    'PPSRR',
    'PPSRP',
    'PPSRS',
    'PPSPR',
    'PPSPP',
    'PPSPS',
    'PPSSR',
    'PPSSP',
    'PPSSS',
    'PSRRR',
    'PSRRP',
    'PSRRS',
    'PSRPR',
    'PSRPP',
    'PSRPS',
    'PSRSR',
    'PSRSP',
    'PSRSS',
    'PSPRR',
    'PSPRP',
    'PSPRS',
    'PSPPR',
    'PSPPP',
    'PSPPS',
    'PSPSR',
    'PSPSP',
    'PSPSS',
    'PSSRR',
    'PSSRP',
    'PSSRS',
    'PSSPR',
    'PSSPP',
    'PSSPS',
    'PSSSR',
    'PSSSP',
    'PSSSS',
    'SRRRR',
    'SRRRP',
    'SRRRS',
    'SRRPR',
    'SRRPP',
    'SRRPS',
    'SRRSR',
    'SRRSP',
    'SRRSS',
    'SRPRR',
    'SRPRP',
    'SRPRS',
    'SRPPR',
    'SRPPP',
    'SRPPS',
    'SRPSR',
    'SRPSP',
    'SRPSS',
    'SRSRR',
    'SRSRP',
    'SRSRS',
    'SRSPR',
    'SRSPP',
    'SRSPS',
    'SRSSR',
    'SRSSP',
    'SRSSS',
    'SPRRR',
    'SPRRP',
    'SPRRS',
    'SPRPR',
    'SPRPP',
    'SPRPS',
    'SPRSR',
    'SPRSP',
    'SPRSS',
    'SPPRR',
    'SPPRP',
    'SPPRS',
    'SPPPR',
    'SPPPP',
    'SPPPS',
    'SPPSR',
    'SPPSP',
    'SPPSS',
    'SPSRR',
    'SPSRP',
    'SPSRS',
    'SPSPR',
    'SPSPP',
    'SPSPS',
    'SPSSR',
    'SPSSP',
    'SPSSS',
    'SSRRR',
    'SSRRP',
    'SSRRS',
    'SSRPR',
    'SSRPP',
    'SSRPS',
    'SSRSR',
    'SSRSP',
    'SSRSS',
    'SSPRR',
    'SSPRP',
    'SSPRS',
    'SSPPR',
    'SSPPP',
    'SSPPS',
    'SSPSR',
    'SSPSP',
    'SSPSS',
    'SSSRR',
    'SSSRP',
    'SSSRS',
    'SSSPR',
    'SSSPP',
    'SSSPS',
    'SSSSR',
    'SSSSP',
    'SSSSS'
  ];
};
